# SonarCloud Configuration
sonar.projectKey=ye1sultan_min-chat-backend
sonar.organization=ye1sultan

# Project Information
sonar.projectName=mini-chat-backend
sonar.projectVersion=1.0.0

# Source Code
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,.github/**

# Language
sonar.javascript.node.maxspace=4096

